
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: apollo_api_development

test:
  <<: *default
  database: apollo_api_test

production:
  <<: *default
  database: apollo_api_production
  username: apollo_api
  password: <%= ENV["APOLLO_API_DATABASE_PASSWORD"] %>
  host: db
